name: "Polier Pro"
description: "Baustellenmanagement fuer Poliere"
version: "1.0.24"
slug: "polier_pro"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  8099/tcp: 3001
ports_description:
  8099/tcp: "Polier Pro Web-Interface"
panel_icon: "mdi:hard-hat"
panel_title: "Polier Pro"
panel_admin: true
homeassistant_api: false
hassio_api: false
options: {}
schema: {}
image: "ghcr.io/gianlucako95/polier-pro-addon/{arch}"
